image: Visual Studio 2019

environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    MINGW: mingw64

  - TARGET: i686-pc-windows-msvc
    MINGW: mingw32

  - TARGET: x86_64-pc-windows-gnu
    MINGW: mingw64

  - TARGET: i686-pc-windows-gnu
    MINGW: mingw32

install:
  - C:\msys64\msys2_shell.cmd -defterm -no-start -%MINGW%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test
