[package]
name = "single-instance"
version = "0.1.0"
authors = ["wlbf <lbf1353@live.com>"]

[dependencies]
failure = "0.1.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["synchapi", "winnt", "errhandlingapi", "winerror", "handleapi"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
